[build]
    command = "yarn build"
    publish = "build"

[context.production.environment]
    REACT_APP_CLIENT_ID="827941663791382568"
    REACT_APP_REDIRECT_URI="https://packing-cashout.netlify.app/login"
    REACT_APP_API_URL="https://api.packcord.com"

[[redirects]]
    from = "/*"
    to = "/"
    status = 200
